-- creates a table with 4 columns
-- IF NOT EXISTS - prevents CREATE TABLE 
-- from executing when one already exists
CREATE TABLE IF NOT EXISTS whopipe_video_views (
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_name TEXT NOT NULL,
    region TEXT NOT NULL,
    date_viewed TIMESTAMP DEFAULT now() NOT NULL
);

-- department , ENUM
-- ENUM is a list of options that may be used by columns
-- CREATE TYPE doesnt support IF NOT EXISTS so we remove
-- the type if it does exist first
DROP TYPE IF EXISTS department;
CREATE TYPE department AS ENUM (
    'Electronics',
    'Cleaning',
    'Grocery',
    'Furniture',
    'Stationery',
    'Clothing',
    'DIY',
    'Sports',
    'Homeware',
    'Games',
    'Transport'
);

-- creates a table with 5 columns
-- price, set to decimal, which can be 12 in 'precision' and 2 decimal points
-- category, data type of department which is the ENUM we created above
-- if 'Electronics' is used as the value, that's fine, but if 'Foo'
-- is used as a value, it won't work because it isnt in the ENUM list of poss. values
CREATE TABLE IF NOT EXISTS amazong_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    image TEXT,
    category department NOT NULL
);