-- Create table called shopping_list
CREATE TABLE IF NOT EXISTS shopping_list (
    item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    category grocery NOT NULL,
    checked BOOLEAN NOT NULL DEFAULT FALSE,
    date_added TIMESTAMP DEFAULT now() NOT NULL
);

-- Create type called grocery
-- Drop type if exists first
DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);